name: Build

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.tag.outputs.exists }}
      version: v${{ steps.version.outputs.version }}
      commit: ${{ steps.commit.outputs.status }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Seo-4d696b75/station_database

      - name: Get database version
        id: version
        run: |
          VERSION=$(cat latest_info.json | jq '.version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: tag
        with:
          tag: v${{ steps.version.outputs.version }}

      - name: Check need commit
        id: commit
        run: |
          LAST_COMMIT=$(git log --date=unix --pretty=format:"%ad" -1)
          CURRENT_TIME=$(date +%s)

          if [ $(($CURRENT_TIME - $LAST_COMMIT)) -gt 2592000 ]; then
            echo "status=true" >> $GITHUB_OUTPUT
          else
            echo "status=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: ${{ needs.check.outputs.skip != 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout master repository
        uses: actions/checkout@v4
        with:
          repository: Seo-4d696b75/station_database
          path: station_database

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run
        run: deno run --allow-read --allow-write build.ts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.check.outputs.version }}
          body: |
            このリリースはGithub Actionsによって自動生成されました。
            駅情報の更新については以下のChangelogを参照してください。
            [Changelog](https://github.com/Seo-4d696b75/station_database/releases/tag/${{ needs.check.outputs.version }})
          tag_name: ${{ needs.check.outputs.version }}
          files: station_database.msgpack
          token: ${{ secrets.GITHUB_TOKEN }}

  # 最終コミットから30日以上経過している場合は空コミットを行う (cronの停止対策)
  commit:
    needs: check
    if: ${{ needs.check.outputs.commit == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit
        run: |
          git commit --allow-empty -m "chore: prevent automatic workflow stopping" -m "see: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
          git push